---
- name: Install mpivars
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22' or ansible_distribution_major_version == '24'
  block:
    - name: Get the openmpi version # noqa command-instead-of-shell no-changed-when
      ansible.builtin.shell:
        cmd: ls /usr/mpi/gcc/
      register: openmpi
      failed_when: false

    - name: Check if mpivars.sh exists
      ansible.builtin.stat:
        path: /usr/mpi/gcc/{{ openmpi.stdout_lines[0] }}/bin/mpivars.sh
      register: mpivars
      when: openmpi.stdout_lines | length > 0

    - name: Create mpivars.sh
      become: true
      ansible.builtin.template:
        src: mpivars.j2
        dest: /usr/mpi/gcc/{{ openmpi.stdout_lines[0] }}/bin/mpivars.sh
        force: true
        owner: root
        group: root
        mode: '0755'
      when: openmpi.stdout_lines | length > 0 and not mpivars.stat.exists
