---
- name: Install perftest
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22' or ansible_distribution_major_version == '24'
  block:

    - name: Clone perftest github repository
      ansible.builtin.git:
        repo: https://github.com/linux-rdma/perftest.git
        dest: /opt/oci-hpc/perftest
        clone: true
        update: true
        version: 318288ee9fe2db8ba34d9b2032831aa401ba8e5d

    - name: Install libpci-dev
      ansible.builtin.apt:
        name: libpci-dev
        lock_timeout: 300

    - name: Run autogen
      ansible.builtin.shell: |
        bash autogen.sh
      args:
        chdir: "/opt/oci-hpc/perftest"
        creates: "/opt/oci-hpc/perftest/configure"

    - name: Configure the directory
      ansible.builtin.shell: |
        ./configure --prefix=/opt/oci-hpc/perftest/ --enable-rocm --with-rocm=/opt/rocm
      args:
        chdir: "/opt/oci-hpc/perftest"
        creates: "/opt/oci-hpc/perftest/Makefile"

    - name: Build perftest
      community.general.make:
        chdir: "/opt/oci-hpc/perftest"

    - name: Install perftest
      community.general.make:
        chdir: "/opt/oci-hpc/perftest"
        target: install
